version: '3'

services:
  discovery-service:
    image: docker.io/nocdentallab/discovery-server:latest

  enrollment-service:
    image: docker.io/nocdentallab/enrollment-service:latest
    depends_on:
      - discovery-service

  doctor-service:
    image: docker.io/nocdentallab/doctor-service:latest
    depends_on:
      - discovery-service
      - enrollment-service

  lab-service:
    image: docker.io/nocdentallab/lab-service:latest
    depends_on:
      - discovery-service
      - enrollment-service
      - doctor-service

  gateway-service:
    image: docker.io/nocdentallab/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - enrollment-service
      - doctor-service
      - lab-service

